sudo: required
services:
  - docker

before_install:
  - docker build -t parthi22/d3chart-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true parthi22/d3chart-client npm run test -- --coverage

after_success:
  - docker build -t parthi22/d3chart-client ./client
  - docker build -t parthi22/d3chart-api ./server
  - docker build -t parthi22/d3chart-nginx ./nginx
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  
  - docker push parthi22/d3chart-api
  - docker push parthi22/d3chart-nginx
  - docker push parthi22/d3chart-client

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: d3chart
  env: D3chart-env
  bucket_name: elasticbeanstalk-ap-south-1-764990977356
  bucket_path: d3chart
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY